### PR TITLE
model/migration for chess app

### PR DESCRIPTION
**Pull request by mahalocode**
- Adding model  and migration for our chess app. Please review code and merge on green! 
- It would be wise to review and  manually merge in case there's a conflict.

-Built CRUD for game model, not sure if I have it all there(review needed)

**Some issues`**
-  We haven't define "available" in controller and views/index which gave an error. We can go back and edit later. 
- I added the test that Dan posted on Trello. Though it did not fail, the test is in a pending state at the moment.

Let me know what else can be improve!

Tom.

### CODE REVIEW

**Comment by mahalocode** [comment]
I also delete id from migration table since it caused an issue to migrate. If we want to add "id" back in, StackOverflow suggested we define a custom primary key to false. I will need another opinion on that.

**Comment by icrustandi** [comment]
@mahalocode the migration files look good to me. I think the instance variables for the new, create, update, and destroy methods should be in the singular form (@available_game instead of games). The only place where it should be plural is when we're listing Game.all. Let me know what you think

**Comment by mahalocode** [comment]
@icrustandi Great! Merge ready then?

**Comment by mahalocode** [comment]
@crossphd STI doesn't seem to be enjoying itself in our pancakes folder. @danielpowell4 did explain that we shouldn't worry about failed check. We may need to talk to everyone so we all can agree on steps to take.

**Comment by danielpowell4** [comment]
The builds are failing for all of these.

**Almost all due to robocop complaints.**

Please fix this before merging in. Either by actually fixing (preferred) or adding things you disagree with the exceptions file.

Also, the `create` action on the games controller is relying on a `games[:params]` method that is typically defined as a private action below. No such action is found.

If you aren't feeling tracing each step through, you could rebuild the models as scaffolds which auto-generate most suspected behavior (CRUD and others)

**Comment by danielpowell4** [comment]
Also when I went to stage a change after running `rake db:migrate` the whole schema wasn't staged (`player_id`).

Please add and commit this to this PR before moving forward

**Comment by mahalocode** [comment]
Not a good idea to use scaffold since it auto generate extra things we don't want, but I'll  fix it before merge.

**Comment by danielpowell4** [comment]
You can always just delete the extra files it makes pre commit. But I agree in principle. I was looking for the easiest way possible to get things done

**Comment by crossphd** [comment]
I just reviewed the models and the migrations in the pull request and those look pretty good to me.

**Comment by mahalocode** [comment]
Cool. I'll go ahead and merge it.

**Pull request merged**
