### PR TITLE
Add drag and drop to board, model fixes

### PR DESCRIPTION
**Pull request by icrustandi**
### What does this PR do?
Drag/drop pieces on the board now works!

### Where should I start?
[Add filenames here. If you were explaining this PR to someone else, with which files would you begin your tour?]
app/views/games/show.html.erb
app/views/layouts/application.html.erb

### How do I manually test this?
Standard pull and rails s, start a game, and check out the drag and drop.

### Additional Comments
This took me way longer than it should have because it kept giving me an "unprocessable entity" error in the console. It turned out that adding the jQuery scripts caused the error, regardless of the code that I wrote. In the last place I looked, the console where the rails server was running, the following error happens "Can't verify CSRF token authenticity." A bit of Googling told me it was an issue with csrf tokens not being passed through in the AJAX call. Adding a single line helped fix that. Keep this in mind when doing other AJAX calls within the app.
 
Note: I tried to use .board as the draggable container, but it's a bit off and clipped on the left side. I'll see if I can fix that. If the container worked properly, the revert parameter isn't required.

### CODE REVIEW

**Comment by mahalocode** [comment]
Drag and drop work partially. it seems to return back when I tried to drag and drop the pawn, it returns to its original spot.

**Comment by icrustandi** [comment]
@mahalocode It should only return to the original spot if it gets dragged outside of the board. Where is the pawn being dragged from and dragged to? Is it possible to show me a screen recording somehow?

**Comment by mahalocode** [comment]
@icrustandi Huh. It works perfectly fine now. Maybe it was a glitch on my part. Great job!

**Comment by icrustandi** [comment]
huh, weird. Let me know if it comes up again!

**Pull request merged**
